name: mydartlearning
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'  # install this extension:  pubspec  to install use : dart pub get 

dependencies:
  path: ^1.8.0
  #riverpod: ^0.13.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  pedantic: ^1.9.0
